---
# Lint for Drupal and other Coding Standards.
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Lint Code Base

# Start the job on all pushes and PRs
on:
  push:
    branches-ignore: [main]
  pull_request:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      # Setup composer and the Drupal coding standards
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer Downloads
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer dependencies
        uses: php-actions/composer@v2
      - name: Check coding standards
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          # Will only run linters listed
          # https://github.com/github/super-linter#environment-variables
          VALIDATE_PHP_PHPCS: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
      - run: ls -al super-linter.report
      - run: cat super-linter.report
      - name: Upload Report as an artifact
        uses: actions/upload-artifact@master
        with:
          name: linter-report
          path: super-linter.report
